name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ 'feature**' ]
  pull_request:
    branches: [ 'feature**' ]
    

jobs:
  initial-setup:
    name: Initial setup
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.8'
    - name: Installing dependencies and libraries
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Run tests
      id: run-tests
      run: pytest
  
  merges:
    needs: initial-setup
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Complete') }}
    steps:
    - name: Merge feature -> develop
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: ${{ github.ref }}
        target-branch: develop
    - name: Checkout
      uses: actions/checkout@v2    
    - name: Create branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git checkout -b release
        git push -f -u origin release
    - name: Mege release -> main
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: release
        target-branch: main